### PR TITLE
#2: Add no-unnamed-types (closes #2)

### LINKED ISSUE #2: Add no-unnamed-types
All tcomb combinators accept a name. For most of them the name is optional.

This rule enforces the presence of a name when declaring a new type.

This rule should allow deciding which combinators should have a name enforced and provide some sensible defaults. E.g. the `t.struct` combinator should always have a name by default, but the `t.list` combinator probably shouldn't.

### PR DESCRIPTION
**Pull request by gabro**
Issue #2

### CODE REVIEW

**Comment by gabro** [comment]
@giogonzo take a look.

As discussed offline, `MyType.extend` is not checked (see note in docs)

**Comment by giogonzo** [comment]
Nice!

**Comment by gabro** [comment]
Oops, just realized default configuration still uses enabled instead of disabled. I'll open an issue to fix it

**Comment by giogonzo** [comment]
yes sorry, merged too quickly:

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at isTcombCombinatorCall (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint-plugin-tcomb/lib/rules/no-unnamed-types.js:46:32)
    at EventEmitter.checkName (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint-plugin-tcomb/lib/rules/no-unnamed-types.js:58:12)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/gonzo/Projects/aliniq/labonline/web/node_modules/estraverse/estraverse.js:501:28)
```

(on LOL)

I'll look into this

**Comment by gabro** [comment]
ouch. Yes, please add test cases as you see fit

**Pull request merged**
